name: First Action

# Runs manually
on: workflow_dispatch

jobs:
  first-job:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
        - name: Print greeting
          run: echo "Hello World"
        - name: Print bye
          run: echo "Run bye"
          
        # Ues a pipe to run multiple commands in 1 to make it an 'array' of commands to run in 1
        - name: MultiLine command
          run: |
            echo "First"
            echo "Second"
            echo "Third"
        
