name: Deploy

# On commit or manual run.
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # These do not run in the repo, just on a machine with github. So we need get it onto the runner
      # Actions: complex repeated task. 
      # https://github.com/marketplace
      # https://github.com/actions/checkout
      - name: Get code
        uses: actions/checkout@v3 

      # npm is already installed per:
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      # Though we will do an upgrade here for version 18
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run test
        run: npm test

  lint:  
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  # By default this job would run in parallel. So instead we depend on test before deploy
  deploy:
    needs: "test"
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          # personal access token, set in the repos settings
          # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          # Found at
          # https://github.com/settings/tokens?type=beta
          # https://github.com/settings/personal-access-tokens/new
          token: ${{ secrets.GH_PAT }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          # uses a secret token so that it can push up the page
          token: ${{ secrets.GH_PAT }}

